# Линейная алгебра

## Урок 2. Матрицы и матричные операции

### Часть 1

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) Матрица $AB$ не определена, так как число столбцов матрицы $A$ $\neq$ числу строк матрицы $B$: $2\neq4$       
Матрица $BA$ не определена, так как число столбцов матрицы $B$ $\neq$ числу строк матрицы $A$: $4\neq2$

б) Матрица $AB$ определена, так как число столбцов матрицы $A$ = числу строк матрицы $B$, размер матрицы $AB=2\times3$       
Матрица $BA$ не определена, так как число столбцов матрицы $B$ $\neq$ числу строк матрицы $A$: $3\neq2$

в) Матрица $AB$ определена, так как число столбцов матрицы $A$ = числу строк матрицы $B$, размер матрицы $AB=8\times8$       
Матрица $BA$ определена, так как число столбцов матрицы $B$ = числу строк матрицы $A$, размер матрицы $AB=3\times3$

г) Матрицы $AB$ и $BA$ определены, размер матриц $4\times4$   

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Проверим с numpy

In [1]:
import numpy as np

a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица A + B\n{a + b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица A + B
[[ 5 -3]
 [ 3  5]]


$A\cdot B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot 4+(-2)\cdot 0 & 1\cdot (-1)+(-2)\cdot 5\\ 
3\cdot 4+0\cdot 0 & 3\cdot (-1)+0\cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$B\cdot A=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4\cdot 1+(-1)\cdot 3 & 4\cdot (-2)+(-1)\cdot 0\\ 
0\cdot 1+5\cdot 3 & 0\cdot (-2)+5\cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [2]:
print(f'Матрица AB\n{np.dot(a, b)}')
print(f'Матрица BA\n{np.dot(b, a)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица C\n{c}\n')
print(f'Матрица 3A - 2B + 4C\n{3*a - 2*b + 4*c}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$

$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot 4+1\cdot 1 & 4\cdot 5+1\cdot(-2) & 4\cdot 2+1\cdot3\\
5\cdot 4+(-2)\cdot 1 & 5\cdot 5+(-2)\cdot (-2) & 5\cdot 2+(-2)\cdot 3\\
2\cdot 4+3\cdot 1 & 2\cdot 5+3\cdot (-2) & 2\cdot 2+3\cdot 3\\
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot 4+5\cdot 5+2\cdot 2 & 4\cdot 1+5\cdot (-2)+2\cdot 3 \\
1\cdot 4+(-2)\cdot 5+3\cdot 2 & 1\cdot 1+(-2)\cdot (-2)+3\cdot 3
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(np.dot(a, a.T)) 
print(np.dot(a.T, a))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def multiplicate_matrix(left,right):
    try: 
        left.shape[1]==right.shape[0]
        result=[]
        temp=[]
        s=0
        for i in range(left.shape[0]):
            for j in range(right.shape[1]):
                for k in range(right.shape[0]):
                    s+=left[i][k]*right[k][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]
        return np.array(result)
    except Exception:
        print('Произведение матриц таких размеров не определено!')

In [6]:
A=np.array([[7, -4],[0, 0],[5, 2],[-3, 1]])
B=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
C=np.array([[3, 5, 7], [-2, 1, 0], [-2, 3, 5]])

In [7]:
A.dot(B)

array([[-13, -10,  -7,  -4],
       [  0,   0,   0,   0],
       [ 15,  22,  29,  36],
       [  2,   0,  -2,  -4]])

In [8]:
multiplicate_matrix(A,B)

array([[-13, -10,  -7,  -4],
       [  0,   0,   0,   0],
       [ 15,  22,  29,  36],
       [  2,   0,  -2,  -4]])

In [9]:
B.dot(A)

array([[10,  6],
       [46,  2]])

In [10]:
multiplicate_matrix(B,A)

array([[10,  6],
       [46,  2]])

In [11]:
A.dot(C)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [12]:
multiplicate_matrix(A,C)

Произведение матриц таких размеров не определено!


### Часть 2

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $det=sinx \cdot sinx - cosx \cdot (-cosx)=sin^2x+cos^2x=1$          
б) Так как матрица треугольная, то **определитель равен произведению элементов, стоящих на ее главной диагонали**: $4 \cdot 5 \cdot 9=180$       
в) Разложим по элементам первой строки:               
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot \begin{vmatrix}
5 & 6\\ 
8 & 9 
\end{vmatrix} - 2 \cdot \begin{vmatrix}
4 & 6\\ 
7 & 9 
\end{vmatrix} + 3 \cdot \begin{vmatrix}
4 & 5\\ 
7 & 8 
\end{vmatrix} = (5 \cdot 9-6\cdot 8)-2\cdot(4\cdot 9-6\cdot 7)+3\cdot(4\cdot 8-5\cdot 7)=(45-48)-2\cdot(36-42)+3\cdot(32-35) = -3+12-9=0$

In [13]:
for x in range(0,11,2):
    A=np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
    print(x, round(np.linalg.det(A)))

0 1
2 1
4 1
6 1
8 1
10 1


In [14]:
B=np.array([[4,2,3], [0,5,1],[0,0,9]])  
np.linalg.det(B)

180.0

In [15]:
C=np.array([[1,2,3], [4,5,6],[7,8,9]])  
np.linalg.det(C)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2})=16$, так как **для двух квадратных матриц одинакового размера:** $det(AB)=detA\cdot detB$          
б) $det(A^{T})=4$, так как **Определитель транспонированной матрицы равен определителю исходной:** $detA^{T}=detA$  
в) $det(2A)=2^{n}\cdot det(A)=2^{n}\cdot 4$, где $n$ - порядок матрицы $A$, так как **умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число**

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Для этого надо доказать, что определитель матрицы равен 0.

В данной матрице $2 строка = -2 \cdot (1 строка)$, то есть $\begin{pmatrix}4 & -14 & 6\end{pmatrix}=-2 \cdot \begin{pmatrix}-2 & 7 & -3\end{pmatrix}$, то есть они линейно зависимы, а **если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю**, значит матрицы вырожденная

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) $3 строка = 1 строка + 2 строка$, значит 3 строку можно выкинуть          
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$                  

Далее вычтем 2 строку из 1 и поменяем их местами                
$$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$$ 

Получаем 2 ненулевых строка, значит **ранг матрицы 2**

б) $3 строка = 1 строка + 2 строка$, значит 3 строку можно выкинуть, так же поменяем первую и последнюю строки местами     
$$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1
\end{pmatrix}$$

Далее вычтем из 3 строки 2
$$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1
\end{pmatrix}$$

Получаем 3 ненулевых строки, значит **ранг матрицы 3**